# Generated by Django 4.0.3 on 2022-03-15 23:02

from msilib.schema import Class
from unicodedata import name
from django.db import migrations

#from character_builder you have to import each class that you are going to be using to add a table
from character_builder.models import ClassStartingStats


bandit_dict = {
    "base_lvl"  : 5,
    "base_vig" : 10,
    "base_mnd" : 11,
    "base_end" : 10,
    "base_str" : 9,
    "base_dex" : 13,
    "base_int" : 9,
    "base_fai" : 8,
    "base_arc" : 14
}

astrologer_dict = {
    "base_lvl"  : 6,
    "base_vig" : 9,
    "base_mnd" : 15,
    "base_end" : 9,
    "base_str" : 8,
    "base_dex" : 12,
    "base_int" : 16,
    "base_fai" : 7,
    "base_arc" : 9
}

warrior_dict = {
    "base_lvl"  : 8,
    "base_vig" : 11,
    "base_mnd" : 12,
    "base_end" : 11,
    "base_str" : 10,
    "base_dex" : 16,
    "base_int" : 10,
    "base_fai" : 8,
    "base_arc" : 9
}

prisoner_dict = {
    "base_lvl"  : 9,
    "base_vig" : 11,
    "base_mnd" : 12,
    "base_end" : 11,
    "base_str" : 11,
    "base_dex" : 14,
    "base_int" : 14,
    "base_fai" : 6,
    "base_arc" : 9
}

confessor_dict = {
    "base_lvl"  : 10,
    "base_vig" : 10,
    "base_mnd" : 13,
    "base_end" : 10,
    "base_str" : 12,
    "base_dex" : 12,
    "base_int" : 9,
    "base_fai" : 14,
    "base_arc" : 9
}

wretch_dict = {
    "base_lvl"  : 1,
    "base_vig" : 10,
    "base_mnd" : 10,
    "base_end" : 10,
    "base_str" : 10,
    "base_dex" : 10,
    "base_int" : 10,
    "base_fai" : 10,
    "base_arc" : 10
}

vagabond_dict = {
    "base_lvl"  : 9,
    "base_vig" : 15,
    "base_mnd" : 10,
    "base_end" : 11,
    "base_str" : 14,
    "base_dex" : 13,
    "base_int" : 9,
    "base_faith" : 9,
    "base_arc" : 7
}

prophet_dict = {
    "base_lvl"  : 7,
    "base_vig" : 10,
    "base_mnd" : 14,
    "base_end" : 8,
    "base_str" : 11,
    "base_dex" : 10,
    "base_int" : 7,
    "base_fai" : 16,
    "base_arc" : 10
}

samurai_dict = {
    "base_lvl"  : 9,
    "base_vig" : 12,
    "base_mnd" : 11,
    "base_end" : 13,
    "base_str" : 12,
    "base_dex" : 15,
    "base_int" : 9,
    "base_fai" : 8,
    "base_arc" : 8
}

def populate(app, schema_editor):
    yeet = ClassStartingStats.objects.get(name = 'Hero')
    yeet.base_vig = 14
    yeet.base_mnd = 9
    yeet.base_end = 12
    yeet.base_str = 16
    yeet.base_dex = 9
    yeet.base_int = 7
    yeet.base_fai = 8
    yeet.base_arc = 11
    yeet.save()
    # Say you make a mistake and need to change a row, follow format below
    #var = ClassStartingStats.objects.get(name='mistaken_row')
    #var.base_lvl = 24
    #var.name = "Vagabond"
    #var.save()
    #From there run python manage.py makemigrations character_builder
    #Then python manage.py migrate
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0002_alter_classstartingstats_base_lv'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
