# Generated by Django 4.0.3 on 2022-03-16 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0004_classstartingstats_base_arc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classstartingstats',
            old_name='base_lv',
            new_name='base_lvl',
        ),
    ]
