# Generated by Django 4.0.3 on 2022-03-16 01:45

from django.db import migrations, models
from character_builder.models import ClassStartingStats

class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0003_auto_20220315_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstartingstats',
            name='base_arc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classstartingstats',
            name='base_dex',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classstartingstats',
            name='base_end',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classstartingstats',
            name='base_fai',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classstartingstats',
            name='base_int',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classstartingstats',
            name='base_mnd',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classstartingstats',
            name='base_str',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classstartingstats',
            name='base_vig',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    
    ]
