# Generated by Django 4.0.3 on 2022-03-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_builder', '0005_rename_base_lv_classstartingstats_base_lvl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classstartingstats',
            old_name='base_lvl',
            new_name='base_lv',
        ),
    ]
